version: 0.2

phases:
  install:
    commands:
      - echo "📦 Installing deployment dependencies"
      - pip install --upgrade pip
      - pip install sagemaker boto3

  build:
    commands:
      - echo "🚀 Deploying model to SageMaker"
      - python scripts/deploy.py
      - echo "✅ Deployment script finished (endpoint creation async)"
