version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install sagemaker scikit-learn pandas joblib

  build:
    commands:
      - echo "📦 Packaging model artifacts..."
      - mkdir model
      - cp fraud_model.pkl model/
      - cp inference.py model/
      - tar -czvf fraud_model.tar.gz -C model .
      - echo "🚀 Deploying model to SageMaker..."
      - python deploy.py

artifacts:
  files:
    - fraud_model.tar.gz
    - deploy.py
